site_name: User Guide
site_url: https://pixora.github.io/yoc-user-guide/
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    primary: cyan
    accent: indigo
  features:
    - navigation.expand
    - navigation.tabs
    - i18n.alternates
plugins:
  - search
  - i18n:
      default_language: it
      languages:
        - locale: it
          name: Italiano
          default: true
          build: true
        - locale: en
          name: English
          default: false
          build: true
      exclude: assets/* ```
  - print-site:
      add_to_navigation: true
      print_page_title: 'Print'
      add_print_site_banner: true
      print_site_banner_template: "./docs/assets/templates/custom_banner.tpl"
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: "./docs/assets/templates/cover.tpl"
      path_to_pdf: ""
      include_css: true
      enabled: true
      exclude:
